// mount.cpp : implementation file
//

#include "stdafx.h"
#include "ZeroBlockMT.h"
#include "mount.h"
#include "afxdialogex.h"


// mount dialog

IMPLEMENT_DYNAMIC(mount, CDialogEx)

mount::mount(CWnd* pParent /*=NULL*/)
	: CDialogEx(mount::IDD, pParent)
	, m_nb(0)
	, m_ut(0)
	, m_nonce(0)
{
	m_nonce = 0;
	m_ut = 0;
	m_nb = 0;
	m_pkey = _T("");
	m_timestamp = _T("");
}

mount::~mount()
{
}

/* autogenerated after Add member var . token->editbox charge arranged by OnInitDialog where vice versa charge 
  by OnOk . UpdateData(0/1)  can be used  .*/
void mount::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
	DDX_Text(pDX, IDC_RICHEDIT21, m_pkey);
	DDV_MaxChars(pDX, m_pkey, 65);
	DDX_Text(pDX, IDC_RICHEDIT22, m_timestamp);
	DDV_MaxChars(pDX, m_timestamp, 254);
	DDX_Text(pDX, IDC_RICHEDIT23, m_nb);
	DDX_Text(pDX, IDC_RICHEDIT24, m_ut);
	DDX_Text(pDX, IDC_RICHEDIT25, m_nonce);
}

BEGIN_MESSAGE_MAP(mount, CDialogEx)
	ON_BN_CLICKED(IDC_BUTTON1, &mount::OnBnClickedButton1)
END_MESSAGE_MAP()

// mount message handlers

void mount::OnBnClickedButton1()
{
	this->OnOK();
}

